query Profile($login: String!) {
  user(login: $login) {
    id
    name
    url
    avatarUrl
    login
    company
    followers {
      totalCount
    }
    following {
      totalCount
    }
  }
}
